app = "probation-seller"
primary_region = "sin"

[build]

[vm]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/healthz"
